# Numpy

Quickstart tutorial: https://numpy.org/doc/stable/user/quickstart.html

In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
# 0d
arr = np.array(5)
print(f"dims: {arr.ndim}")
print(f"shape: {arr.shape}")
arr

dims: 0
shape: ()


array(5)

In [12]:
# 1d
arr = np.arange(5)
print(f"shape: {arr.shape}")
arr

shape: (5,)


array([0, 1, 2, 3, 4])

In [13]:
# 2d
arr = np.arange(15).reshape(3, 5) # reshape args are the length of each axis
print(f"dims: {arr.ndim}")
print(f"shape: {arr.shape}")
arr

dims: 2
shape: (3, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
# 3d
arr = np.arange(30).reshape(3, 5, 2)
print(f"dims: {arr.ndim}")
print(f"shape: {arr.shape}")
arr

dims: 3
shape: (3, 5, 2)


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [17]:
#types

print(np.array([1,2,3]).dtype)
print(np.array([1.1,2.2,3.3]).dtype)

int64
float64


In [19]:
# creation, defaults to float64

np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.ones(5, dtype="int64")

array([1, 1, 1, 1, 1])

In [44]:
ar1 = np.arange(1, 7).reshape(2, 3)
ar2 = ar1.copy()
print(ar1)
print("sum", ar1 + ar2)
print("product", ar1 * ar2)
print("dot product", ar1 @ ar2.reshape(3, 2))
print("dot product", ar1 @ ar2.reshape(3, 2))
print("dot product", ar1.reshape(3, 2) @ ar2)

[[1 2 3]
 [4 5 6]]
sum [[ 2  4  6]
 [ 8 10 12]]
product [[ 1  4  9]
 [16 25 36]]
dot product [[22 28]
 [49 64]]
dot product [[22 28]
 [49 64]]
dot product [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [51]:
ar1 = np.arange(1, 7).reshape(2, 3)
print(ar1)
print("\nall values")
print("sum: ", ar1.sum())
print("min: ", ar1.min())
print("max: ", ar1.max())
print("mean: ", ar1.mean())

print("\naxes")
print("sum columns: ", ar1.sum(axis=0))
print("sum rows: ", ar1.sum(axis=1))


[[1 2 3]
 [4 5 6]]

all values
sum:  21
min:  1
max:  6
mean:  3.5

axes
sum columns:  [5 7 9]
sum rows:  [ 6 15]
