# Numpy

Quickstart tutorial: https://numpy.org/doc/stable/user/quickstart.html

In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [70]:
arrays = [
    np.array(5), #0d
    np.arange(5), #1d
    np.arange(15).reshape(3, 5), #2d - reshape args are the length of each axis
    np.arange(30).reshape(3, 5, 2), #3d
    np.zeros((2, 2)), # defaults to float64
    np.ones(5, dtype="int64"),
    np.empty((2, 2)), # random initial values
    np.full((2, 2), 7), # filled with 7s
]
for arr in arrays:
    print(f"dims: {arr.ndim}, shape: {arr.shape}, size: {arr.size}\ncontent: {arr}\n")

dims: 0, shape: (), size: 1
content: 5

dims: 1, shape: (5,), size: 5
content: [0 1 2 3 4]

dims: 2, shape: (3, 5), size: 15
content: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

dims: 3, shape: (3, 5, 2), size: 30
content: [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]

dims: 2, shape: (2, 2), size: 4
content: [[0. 0.]
 [0. 0.]]

dims: 1, shape: (5,), size: 5
content: [1 1 1 1 1]

dims: 2, shape: (2, 2), size: 4
content: [[-0.75075912 -0.18682678]
 [-1.13453199 -1.05976176]]

dims: 2, shape: (2, 2), size: 4
content: [[7 7]
 [7 7]]

dims: 2, shape: (2, 2), size: 4
content: [[0.77601248 0.50555398]
 [0.82907173 0.38044966]]



In [73]:
#types
arrays = [
    np.array([1,2,3]), # inferred as int64
    np.array([1.1,2.2,3.3]), # inferred as float64
    np.zeros((3, 2)), # defaults to float64
    np.ones(5, dtype="int64"),
]

for arr in arrays:
    print(f"dytpe: {arr.dtype}")
    print(f"content: {arr}\n")

dytpe: int64
content: [1 2 3]

dytpe: float64
content: [1.1 2.2 3.3]

dytpe: float64
content: [[0. 0.]
 [0. 0.]
 [0. 0.]]

dytpe: int64
content: [1 1 1 1 1]



# Operations

In [75]:
ar1 = np.arange(1, 7).reshape(2, 3)
ar2 = ar1.copy()
print(f"content: {ar1}\n")
print("sum", ar1 + ar2)
print("product", ar1 * ar2)
print("dot product", ar1 @ ar2.reshape(3, 2))
print("dot product", ar1 @ ar2.reshape(3, 2))
print("dot product", ar1.reshape(3, 2) @ ar2)
print("dot product", ar1.reshape(3, 2).dot(ar2))

content: [[1 2 3]
 [4 5 6]]

sum [[ 2  4  6]
 [ 8 10 12]]
product [[ 1  4  9]
 [16 25 36]]
dot product [[22 28]
 [49 64]]
dot product [[22 28]
 [49 64]]
dot product [[ 9 12 15]
 [19 26 33]
 [29 40 51]]
dot product [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


# Aggregate functions

In [79]:
ar1 = np.arange(1, 7).reshape(2, 3)
print(ar1)
print("\nall values")
print(f"sum: {ar1.sum()}, min: {ar1.min()}, max: {ar1.max()}, mean: {ar1.mean()}")

print("\naxes")
print("sum columns: ", ar1.sum(axis=0))
print("sum rows: ", ar1.sum(axis=1))


[[1 2 3]
 [4 5 6]]

all values
sum: 21, min: 1, max: 6, mean: 3.5

axes
sum columns:  [5 7 9]
sum rows:  [ 6 15]


# Slicing

In [107]:
arr = np.arange(15).reshape(3, 5)
print(f"2d: {arr}\n")
print(f"specific value from col 0 row 1: {arr[0, 1]}")
print(f"2nd row: {arr[1]} or {arr[1, :]}")
print(f"last row: {arr[-1]} or {arr[-1, :]}")
print(f"2nd col: {arr[:, 1]}")
print(f"last col: {arr[:, -1]}")
print(f"1st & 2nd rows: {arr[0:2, :]}") # exclusive

arr =  np.arange(3**3).reshape(3,3,3)
print(f"\n3d: {arr}\n")
print(f"specific value from matrix 0, row 1, col 2: {arr[0, 1, 2]}")
print(f"3rd row of 3rd matrix: {arr[2, 2]}")
print(f"3rd matrix: {arr[2, :, :]}")
print(f"3rd matrix: {arr[2, ...]}")
print(f"3rd row of all matrices: {arr[:, 2, :]}")
print(f"3rd col of all matrices: {arr[:, :, 2]}")
print(f"3rd col of all matrices: {arr[..., 2]}")
print(f"Values at row 3 col 3 all matrices: {arr[:, 2, 2]}")

2d: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

specific value from col 0 row 1: 1
2nd row: [5 6 7 8 9] or [5 6 7 8 9]
last row: [10 11 12 13 14] or [10 11 12 13 14]
2nd col: [ 1  6 11]
last col: [ 4  9 14]
1st & 2nd rows: [[0 1 2 3 4]
 [5 6 7 8 9]]

3d: [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

specific value from matrix 0, row 1, col 2: 5
3rd row of 3rd matrix: [24 25 26]
3rd matrix: [[18 19 20]
 [21 22 23]
 [24 25 26]]
3rd matrix: [[18 19 20]
 [21 22 23]
 [24 25 26]]
3rd row of all matrices: [[ 6  7  8]
 [15 16 17]
 [24 25 26]]
3rd col of all matrices: [[ 2  5  8]
 [11 14 17]
 [20 23 26]]
3rd col of all matrices: [[ 2  5  8]
 [11 14 17]
 [20 23 26]]
Values at row 3 col 3 all matrices: [ 8 17 26]


# Iteration

In [112]:
arr = np.arange(4).reshape(2,2)
print(f"{arr}\n")

for row in arr:
    print(row) # first index
    
for x in arr.flat:
    print(x) # each value as a 1d array

[[0 1]
 [2 3]]

[0 1]
[2 3]
0
1
2
3


# Reshaping

In [116]:
arr = np.arange(4).reshape(2,2)
print(f"{arr}\n")
print(f"flattened with ravel(): {arr.ravel()}")
print(f"reshape(4): {arr.reshape(4)}")
print(f"transposed with T: {arr.T}")

[[0 1]
 [2 3]]

flattened with ravel(): [0 1 2 3]
reshape(4): [0 1 2 3]
transposed with T: [[0 2]
 [1 3]]


# Stacking

In [122]:
a = np.arange(4).reshape(2,2)
b = np.arange(4, 8).reshape(2,2)

print(f"a: {a}")
print(f"b: {b}\n")

print(f"np.vstack((a, b)): {np.vstack((a, b))}")
print(f"np.hstack((a, b)): {np.hstack((a, b))}")
print(f"np.column_stack((a, b)): {np.column_stack((a, b))}")

a: [[0 1]
 [2 3]]
b: [[4 5]
 [6 7]]

np.vstack((a, b)): [[0 1]
 [2 3]
 [4 5]
 [6 7]]
np.hstack((a, b)): [[0 1 4 5]
 [2 3 6 7]]
np.column_stack((a, b)): [[0 1 4 5]
 [2 3 6 7]]
